### ISSUE TITLE
Δεν έχω Ethernet αλλά μόνο Wifi

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#1]
https://github.com/CerebruxCode/Archon/blob/6f0f2cd98bffc2215448af3937bfc37c9fc52656/archon.2#L19

Σε περίπτωση που ο χρήστης έχει μόνο Wifi ή έχει ξεκινήσει την εγκατάσταση με χρήση Wifi, στην επανεκκίνηση δεν θα είναι συνδεδεμένος.

**Comment by billniakas** [comment]
Αν προσθέσουμε αυτές τις γραμμές 
``wifi=$(ip link | grep ": "| grep -oE "(w\w+)")``
και μετά
``systemctl enable dhcpcd@$wifi.service``
θα ενεργοποιεί και το wifi

**Comment by cerebrux** [comment]
Δεν φτάνει μόνο αυτό.
με κάποια σειρά 
`wifi=$(ip link | grep ": "| grep -oE "(w\w+)")`
και 
`pacman -S iw wpa_supplicant dialog wpa_actiond`
και μετα 
`systemctl enable netctl-auto@όνομα-κάρτας.service`

**Comment by billniakas** [comment]
Τελικά θα το βάλουμε το wifi ή όχι;
