### ISSUE TITLE
Πρόβλημα με το ext4

### ISSUE THREAD

**Issue by cfanoulis** [CerebruxCode/Archon#122]
Καλησπέρα, και πολλά συγχαρητήρια για την δουλειά σας στο Archon. Δυστυχώς, αντιμετωπίζω το παρακάτω μήνυμα όταν προσπαθώ να το τρέξω σε ένα Virtualbox VM, με το ISO Ιουλίου.
![ΕΙΚΟΝΑ](https://my-code.is-terrible.com/ora4AO.png)

**Comment by billniakas** [comment]
Δοκίμασε ξανά σε νέο VM γιατί βλέπω νότια πηγε να ξανακάνει partition.

**Comment by cfanoulis** [comment]
Νομίζω έφταιγε πώς ο δίσκος ήταν Dynamically allocated, δοκίμασα με fixed size δίσκο και προχώρησε (δεν ολοκλήρωσε όμως, γκρινιάζοντας για τα GPG signatures, θέμα για το οποίο θα ανοίξω καινούργι Issue)

Ευχαριστώ!
