### ISSUE TITLE
Δυνατότητα partitioning 

### ISSUE THREAD

**Issue by lovemytux** [CerebruxCode/Archon#123]
Καταρχάς, πολλά μπράβο για το project.
Πολύ ενδιαφέρουσα δουλειά και θα προσπαθήσω κι εγώ να συνεισφέρω από την πλευρά μου όσο μπορώ. 

Πάμε λοιπόν σε μια μικρή παρατήρηση και κάτι το οποίο θα ήθελα να είχα σαν χρήστης στο setup script.
Θα μπορούσε να δίνεται η δυνατότητα partitioning στο χρήστη. To partitioning δεν χρειάζεται να παρέχει πολλές επιλογές, αλλά κάτι σαν το ακόλουθα (3 βασικές επιλογές):

**Επιλογή ένα (1) - Default επιλογή:**
* 1 partition (για απλούς χρήστες ή γι' αυτούς που θέλουν να testάρουν γρήγορα κάτι) - Το current δηλαδή partition scheme του script

**Επιλογή δύο (2) - Advanced επιλογή:**
* 2 partitions, 1 για root (/) & 1 για home (/home) **

**Επιλογή τρία (3) - Advanced επιλογή:**
* 3 partitions, 1 για root (/), 1 για home (/home) & 1 swap (σε περίπτωση που ο χρήστης δεν θέλει να χρησιμοποιήσει swapfile)

Σαν πρόχειρη σκέψη, στην δεύτερη και τρίτη επιλογή, θα μπορούσαμε να έχει ο χρήστης τη δυνατότητα να δίνει αυτός/ή το μέγεθος των partitions (και σε παρένθεση κάποιες default προκαθορισμένες τιμές).

**Comment by JohnGavr** [comment]
Κάθε βοήθεια είναι ευπρόσδεκτη. Γίνεται μια συζήτηση για την προσθήκη αυτής της δυνατότητας καθώς και για dual boot με Windows. Μπορείς να δεις τα ανοιχτά issue #25 #34

**Comment by cerebrux** [comment]
Τo partitioning μπορεί να γίνει και πριν την εγκατάσταση οπότε δεν χρειάζεται να γίνει εντός του Archon. 
Αν υπάρξει κάποιο pull request το ξανα ανοίγουμε
