### ISSUE TITLE
i3 πρόβλημα εγκατάστασης, πιθανά ελλιπή πακέτα

### ISSUE THREAD

**Issue by lovemytux** [CerebruxCode/Archon#124]
Δοκιμάζοντας τα DE/WM που παρέχονται από το μενού της εγκατάστασης, όταν επιλέξεις το `i3`, εγκαθιστούνται τα αρχεία κανονικά χωρίς κάποιο error, αλλά στο τέλος ο χρήστης παίρνει το ακόλουθο μήνυμα:
**./archon.sh: line 214: /home/root/.xinitrc: No such file or directory**

Παρατήρησα στον κώδικα του script ότι υπάρχει στο block της εγκατάστασης του `i3` το ακόλουθο σετ εντολών:
```
"i3")
                echo -e "${IGreen}Εγκατάσταση i3 Desktop Environment ... \n${NC}"
                installer "i3 Desktop" i3 dmenu rxvt-unicode
                echo -e '#!/bin/bash \nexec i3' > /home/"$USER"/.xinitrc
                exit 0
                ;;
```
Αν αλλαζόταν η μεταβλητή `$USER` σε `$onomaxristi` που είναι και η μεταβλητή που έχει το όνομα του χρήστη που δημιουργείται σε προηγούμενο βήμα της εγκατάστασης, λογικά μπορεί να ξεπεραστεί το πρόβλημα, γιατί θεωρητικά τη στιγμή που καλείται η μεταβλητή `$USER` θα αντιστοιχεί στο root user κι όχι στον χρήστη που δημιουργήθηκε (επιβεβαιώνεται και από το path που παίρνουμε στο error message _/home/root/.xinitrc_).

Υ.Γ.1 Δεν θα έπρεπε να περαστεί το `lightdm`/`lightdm-gtk-greeter` μαζί με το πακέτο `i3`; Πριν από αυτό δεν μπορούσα να πάρω "γραφικό" μετά το login, ενώ πλέον, μετά την εγκατάσταση των παραπάνω πακέτων, φόρτωσε το `lightdm` χωρίς κάποιο πρόβλημα και μπόρεσα να logάρω κανονικά με τον χρήστη μου.

Υ.Γ.2 Δεν έχω τεστάρει ακόμα την αλλαγή του `$USER` -> `$onomaxristi`

**Comment by JohnGavr** [comment]
Γεια σου @lovemytux!

1.Το συγκεκριμένο error το γνωρίζουμε και έχει ήδη λυθεί. Μπορείς αν δεις το αντίστοιχο issue #120. Έχει ήδη περαστεί στο develop και στην επόμενη έκδοση θα ενσωματωθεί στο master.

2. Αν στηθεί σωστά το .xinitrc δεν χρειάζεσαι display manager για να φορτώσει το γραφικό περιβάλλον. Οπότε πιστεύω με την λύση του .xinitrc θα έχεις και το επιθυμητό αποτέλεσμα.

Υ.Γ1: Μπορείς να δοκιμάσεις το develop για να δεις αν όντως λύνεται και με την ευκαιρία να μας δώσεις και ένα feedback.

**Comment by cerebrux** [comment]
Fixed in https://github.com/JohnGavr/Archon/commit/27275aedf94cf737bfd7fd3569307cf3160a3dc2
