### ISSUE TITLE
Dhcpcd-NetworkManager Conflict

### ISSUE THREAD

**Issue by JohnGavr** [CerebruxCode/Archon#126]
Μετά από εγκατάσταση σε περίπτωση που ο χρήστης επιλέξει γραφικό περιβάλλον που εμπεριέχει τον NetworkManager ή τον connman δημιουργείται conflict μεταξύ των services με αποτέλεσμα να γίνεται delay στην εκκίνηση του υπολογιστή. Και ο NetworkManager και ο Connman έχουν ενσωματωμένο dhcp client σύμφωνα με το  [Arch WIki ](https://wiki.archlinux.org/index.php/Network_configuration#Network_managers).

**Comment by cerebrux** [comment]
διορθώθηκε με το https://github.com/CerebruxCode/Archon/pull/129

**Comment by cerebrux** [comment]
Μένει να γίνει merge στο maste
