### ISSUE TITLE
Δυνατότητα χρήστη Lite ή Full εγκατάσταση του Gnome

### ISSUE THREAD

**Issue by giannisjv** [CerebruxCode/Archon#127]
Να δίνεται η δυνατότητα στον χρήστη να επιλέγει αν θέλει να κάνει εγκατάσταση Lite ή Full. Εχω κάνει 3 φορές εγκατάσταση και κάθε φορά κάνω pacman -R gnome-extra. πχ echo -n "Θέλεις Lite ή full εγκατασταση του gnome?" read  choice --> if [ "$choice" == "L" ] echo -e "${IGreen}Εγκατάσταση GNOME Desktop Environment ...\n${NC}"                 installer "GNOME Desktop" gnome                 sudo systemctl enable gdm                 sudo systemctl enable NetworkManager                 exit 0                 ;; elif [ "$choice" == "f" ] echo -e "${IGreen}Εγκατάσταση GNOME Desktop Environment ...\n${NC}"                 installer "GNOME Desktop" gnome gnome-extra                 sudo systemctl enable gdm                 sudo systemctl enable NetworkManager                 exit 0                 ;; else echo "Λαθος απαντηση"

https://github.com/CerebruxCode/Archon/blob/8b14a0d51ced96ed3b437b14ace98add691ba1f7/archon.sh#L152

**Comment by JohnGavr** [comment]
Ωραία επισήμανση @giannisjv . Στην επόμενη έκδοση θα προσπαθήσουμε να το ενσωματώσουμε. 

* Έβαλα τον τίτλο σου στην περιοχή των σχολίων ελπίζω να μην δημιουργηθεί παρεξήγηση.
