### ISSUE TITLE
παραλλήλες λήψεις;

### ISSUE THREAD

**Issue by jemadux** [CerebruxCode/Archon#132]
υπάρχει η δυνατότητα να μπουν οι παραλλήλες λήψεις  ? 
απλα βγάζεις το καγκέλο στο ParrarelDownloads στο /etc/pacman.conf

**Comment by JohnGavr** [comment]
Καλή σαν ιδέα αλλά, το Archon έχει σχεδιαστεί ώστε να στήνει ένα λειτουργικό σύστημα με βάση το installation guide του Arch. 
Με λίγα λόγια, πιστεύω πως είναι στην κρίση του χρήστη να το ενεργοποιήσει και όχι δουλειά του Archon. 

Επίσης, αν κατά την διάρκεια του base install θελήσει να έχει parralel download μπορεί πολύ εύκολο πρωτού τρέξει το script να το ενεργοποιήσει μόνος του.

**Comment by cerebrux** [comment]
Κάλλη σαν ιδέα αλλά θα έπρεπε να το έχουν by default ενεργό στο pre-install οι dev του Arch.

 Για να μην το έχουν (ακόμα) λογικά κάτι θα ξέρουν παραπάνω και το αφήνουν για post-install.

Επειδή το Archon ακολουθεί το Installation του wiki, εφόσον δεν το έχουν ενεργό τότε είναι για post-install.
