### ISSUE TITLE
Grub Kernel Parameters

### ISSUE THREAD

**Issue by JohnGavr** [CerebruxCode/Archon#136]
Για να μπορέσει ο χρήστης να bootαρει πρέπει να προσθετεί στο αρχείο /etc/default/grub η γραμμή

cryptdevice=UUID=device-UUID:root root=/dev/mapper/root

https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#Configuring_the_boot_loader

**Comment by christ4k** [comment]
Επίσης σε περίπτωση που ο δίσκος είναι SSD και υποστηρίζει TRIM πρέπει να γίνουν οι κατάλληλες ενέργειες για να είναι διαθέσιμη αυτή η λειτουργία στον χρήστη

https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)

**Comment by JohnGavr** [comment]
@cerebrux Περιμένουμε την γνώμη σου γύρω από το trim.

**Comment by cerebrux** [comment]
>Επίσης σε περίπτωση που ο δίσκος είναι SSD και υποστηρίζει TRIM πρέπει να γίνουν οι κατάλληλες ενέργειες για να είναι διαθέσιμη αυτή η λειτουργία στον χρήστη
>
>https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)

Είναι θέμα Post Install και δεν επηρεάζει την επιτυχή εγκατάσταση που προσπαθεί να πετύχει το Archon. Το πολύ πολύ να εμφανίσουμε ένα μήνυμα ως υπενθύμιση να ενεργοποιήσει το TRIM  αν το θέλει. Είναι μια systemd υπηρεσία.
