### ISSUE TITLE
Το Systemd-swap δεν ενεργοποιείται

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#14]
https://github.com/CerebruxCode/Archon/blob/f70bdc83368f43b98953d31b8211e78e5fc31bb3/archon.2#L80

Υπάρχει ένα regrassion στο οποίο δεν ενεργοποιείται το Systemd-swap.

το journal εμφανίζει μήνυμα:

`var-lib-systemd-swap-swapfc--1.swap : Value of What= not valid, not loaded.`

Στο τερματικό φαίνεται οτι προσπαθεί να φτιάξει chunks και αποτυγχάνει και έπειτα ξανακάνει μια προσπάθεια.

**Comment by cerebrux** [comment]
Το version 1.0 στο master δεν έχει αυτό το πρόβλημα. Το συναντάμε μονο στο develop branch του v1.1

**Comment by billniakas** [comment]
Αυτό το φτιάχνει χωρίς αριθμό γραμμής
```
sed -i 's/zswap_enabled=1/zswap_enabled=0/' /etc/systemd/swap.conf
sed -i 's/zram_enabled=1/zram_enabled=0/' /etc/systemd/swap.conf
sed -i 's/swapfu_enabled=1/swapfu_enabled=0/' /etc/systemd/swap.conf
sed -i 's/swapfc_enabled=0/swapfc_enabled=1/' /etc/systemd/swap.conf
```
μήπως να κάναμε μια δοκιμή έτσι;

Δοκίμασε το στο branch που κάνεις το bugfix

**Comment by cerebrux** [comment]
https://github.com/Nefelim4ag/systemd-swap/issues/41

Τελικά είναι upstream bug. Στο παραπάνω link έκανα αναφορά οπότε θα το κλείσουμε προσωρινά μέχρι νεοτέρας.
