### ISSUE TITLE
underlying hypervisor specific graphic drivers

### ISSUE THREAD

**Issue by christ4k** [CerebruxCode/Archon#146]
Κατά την εγκατάσταση γραφικού περιβάλλοντος σε Virtual Machine να γίνεται έλεγχος του underlying hypervisor για την εγκατάστη των κατάλληλων drivers.

**Comment by christ4k** [comment]
Μπορεί να χρησιμοποιηθεί έτοιμο script του community της RedHat με όνομα [virt-what](https://people.redhat.com/~rjones/virt-what/) το οποίο κάνει ακριβώς αυτή την δουλειά.
Μετά την ανίχνευση του hypervisor, θα εγκαθιστώνται τα αντίστοιχα πακέτα πάντα σύμφωνα με τις οδηγίες του ArchWiki

**Comment by cerebrux** [comment]
> Μπορεί να χρησιμοποιηθεί έτοιμο script του community της RedHat με όνομα [virt-what](https://people.redhat.com/~rjones/virt-what/) το οποίο κάνει ακριβώς αυτή την δουλειά. Μετά την ανίχνευση του hypervisor, θα εγκαθιστώνται τα αντίστοιχα πακέτα πάντα σύμφωνα με τις οδηγίες του ArchWiki

Καλή ιδέα ! Δοκιμάστε το !
Ταιριάζει με το θέμα στο  #147 ?

**Comment by christ4k** [comment]
> > Μπορεί να χρησιμοποιηθεί έτοιμο script του community της RedHat με όνομα [virt-what](https://people.redhat.com/~rjones/virt-what/) το οποίο κάνει ακριβώς αυτή την δουλειά. Μετά την ανίχνευση του hypervisor, θα εγκαθιστώνται τα αντίστοιχα πακέτα πάντα σύμφωνα με τις οδηγίες του ArchWiki
> 
> Καλή ιδέα ! Δοκιμάστε το ! Ταιριάζει με το θέμα στο #147 ?

Ναι μπορούν να συνδυαστούν σε ένα issue νομίζω.

**Comment by JohnGavr** [comment]
> [virt-what](https://people.redhat.com/~rjones/virt-what/)

Το συγκεκριμένο package βρίσκεται στο AUR και όχι στα Official Repositories. Κάναμε μια εξαίρεση για το yay, για να υπάρχει ένα tool για πρόσβαση στο AUR. 

Περιμένουμε την άποψη σου @cerebrux για να το συνεχίσουμε ή όχι.

**Comment by cerebrux** [comment]
> > [virt-what](https://people.redhat.com/~rjones/virt-what/)
> 
> Το συγκεκριμένο package βρίσκεται στο AUR και όχι στα Official Repositories. Κάναμε μια εξαίρεση για το yay, για να υπάρχει ένα tool για πρόσβαση στο AUR.

Τότε είναι ΝΟ GO !. την πάθαμε μια φορά στις αρχές με πακέτο από AUR, οπότε καλύτερα να γίνει με έναν τρόπο δικό μας.

**Comment by JohnGavr** [comment]
Μετά από λίγο ψάξιμο, υπάρχει το πακέτο [imvirt ](https://archlinux.org/packages/community/x86_64/imvirt/) το οποίο υπάρχει στα Official Repositories του Arch. Έτσι μπορούμε να διαχωρίσουμε το hypervisor και τα πακέτα που εγκαθιστά. 

Θεωρητικά σε μία if - elif αναλόγως τα output που δίνει το εργαλείο.

**Comment by christ4k** [comment]
Η εντολή `dmidecode` μπορεί να μας βοηθήσει, όπως μου υπέδειξε ο @JohnGavr, στην επιλογή με 2 directives που δέχεται. Παραθέτω παραδείγματα που έτρεξα και τα outputs για να έχουμε μία βάση να κινηθούμε:

- VirtualBox

`dmidecode -s system-product-name`
out: `VirtualBox`

`dmicecode -s system-manufacrurer`
out: `innotek GmbH`


- KVM (qemu)

`dmidecode -s system-product-name`
out: `Standard PC (Q35 + ICH9, 2009)`

`dmicecode -s system-manufacrurer`
out: `QEMU`

**Comment by JohnGavr** [comment]
Μετά από συζήτηση με τον @christ4k (και τις πολλές δοκιμές του) και λόγω της περίπτωσης πως το dmidecode μπορεί να εμφανίσει Standard PC σε Virtual ο πρώτος έλεγχος για την διάκριση Bare με Virtual θα γίνεται μέσω του `imvirt`. Στην περίπτωση που είναι Virtual μετά θα γίνεται εγκατάσταση το `dmidecode`. 

Στην περίπτωση που είμαστε σε Virtual θα γίνεται διαχωρισμός σε VirtualBox και QEMU ώστε να γίνονται εγκατάσταση τα απαραίτητα πακέτα.

Για αρχή νομίζω είμαστε καλυμμένοι με αυτά τα δύο. Στο μέλλον ίσως προστεθεί το VMWare.
