### ISSUE TITLE
wrong package installation for Desktop Enviroment on a VM

### ISSUE THREAD

**Issue by christ4k** [CerebruxCode/Archon#147]
Κατά την εγκατάσταση γραφικού περιβάλλοντος σε εικονική μηχανή, γίνεται επιχείρηση εγκατάστασης πακέτου που δεν υπάρχει στα αποθετήρια του Arch Linux.

Το πακέτο έχει το όνομα `virtualbox-guest-dkms`

Να αντικατασταθεί με ό,τι χρειάζεται ή να αφαιρεθεί.

**Comment by cerebrux** [comment]
Συμφωνώ. Μήπως διορθώνεται μαζί με το #146 ?

**Comment by JohnGavr** [comment]
> Συμφωνώ. Μήπως διορθώνεται μαζί με το #146 ?

Ναι, είναι κατηγορία του #146.
