### ISSUE TITLE
No network after Gnome DE installation

### ISSUE THREAD

**Issue by christ4k** [CerebruxCode/Archon#148]
Ως επίλυση προηγούμενου issue (#129) προστέθηκε λειτουργία όπου απενεργοποιείται το `dhcpcd` service μετά την εγκατάσταση γραφικού περιβάλλοντος για την αποφυγή διένεξης με τον `NetworkManager`.

Κατά την εγκατάσταση του `Gnome` είτε χωρίς τα `extra` packets είτε και με, δεν εγκαθίσταται το πακέτο `networkmanager`. Ως συνέπεια κατά την εκκίνηση του συστήματος δεν υπάρχει σύνδεση με το δίκτυο.

Ενέργειες:
- Λύση του παρόντος.
- Διερεύνηση σε ποια άλλα υποστηριζόμενα γραφικά περιβάλλοντα, από τον Archon, θα υπάρξει το ίδιο πρόβλημα.

**Comment by JohnGavr** [comment]
https://wiki.archlinux.org/title/GNOME#Network

Στο Arch Wiki αναφέρει ότι ο NetworkManager είναι μέρος του gnome group. Απ' όσο βλέπω στα depedencies του gnome group πλέον δεν είναι και δεν έχει ενημερωθεί το ArchWiki. Άρα θέλει στην εγκατάσταση του gnome να προστεθεί και το πακέτο networkmanager. 

Σε όλα τα υπόλοιπα Desktop Environment βλέπω πως εγκαθίστανται ξεχωριστά καθώς δεν είναι μέρος των αντίστοιχων group.
