### ISSUE TITLE
Αλλαγή ονόματος στην διαδρομή

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#16]
https://github.com/CerebruxCode/Archon/blob/d14dc047743f36b9a56a3c98f2c9ba87758dc00c/archon.2#L87

το archonswap.conf αν και ωραίο, δεν είναι αντιπροσωπευτικό

θα πρέπει να είναι 

`systemd-swap.conf`

Τι λέτε ?

**Comment by billniakas** [comment]
Ναι, καλύτερα να είναι generic.

**Comment by cerebrux** [comment]
ΟΚ τότε το διορθώνω και το κλείνω.
