### ISSUE TITLE
Προετοιμασία της v1.1

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#17]
- [x] Κλειστά όλα τα bugs και enhancements

- [x] Δημιουργία shortlink https://git.io/Archon

- [x] Αφαίρεση δεύτερου wget απο το Archon.2
- [x] Επικαιροποίηση του README

- [x] Επικαιροποίηση Archon και Archon.2 με note στην αρχή για Άδεια και δημιουργούς

**Comment by billniakas** [comment]
Όταν λες επικαιροποίηση του README τι ακριβώς εννοείς. Δεν έχει κάποιο feature καινούριο, μόνο bugfixing και enhancements. 

Για την επικαιροποίηση των Archon.sh και Archon.2 δεν υπάρχουν έτοιμα templates βάσει της GPL-3 να πετάξουμε μέσα στα αρχεία; Έχει νόημα όμως εφόσον έρχονται μαζί με το LICENSE;

**Comment by cerebrux** [comment]
Είναι απο τα "good" practice να περιλαμβάνεται στην αρχή του κώδικα μια μικρή πληροφόρηση

**Comment by cerebrux** [comment]
Release the Kraken !
