### ISSUE TITLE
Η αναζήτηση με Sed δεν θα πρέπει να γίνεται με αριθμό γραμμής

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#2]
https://github.com/CerebruxCode/Archon/blob/6f0f2cd98bffc2215448af3937bfc37c9fc52656/archon.2#L69

Σε περίπτωση που ο dev του systemd-swap προσθέσει/αφαιρέσει κάτι, υπάρχει περίπτωση να μετακινηθούν η γραμμές η να αλλάξει η αρίθμηση.

**Comment by billniakas** [comment]
εύκολο είναι αυτό
