### ISSUE TITLE
Δεν κατεβαίνει σωστά το script από το shortlink

### ISSUE THREAD

**Issue by billniakas** [CerebruxCode/Archon#23]
Δεν κατεβαίνει σωστά το script από το shortlink. Κατεβαίνει χωρίς κατάληξη και επίσης το unzip δεν είναι εγκατεστημένο στο liveCD του Arch. 

Για να το εγκαταστήσω χρειάστηκε να κατεβάσω manually τα 2 αρχεία (archon.sh και archon.2).

**Comment by cerebrux** [comment]
Παρακαλώ όπως επιβεβαιώσατε ότι το hotfix διορθώνει το κρίσιμο bug.... γιατί θα τους απολύσω όλους !!!

**Comment by billniakas** [comment]
Καλά 
κατούρα και λίγο, με το hotfix όλα είναι εντάξει.
