### ISSUE TITLE
Προσθήκη υποστήριξης για Dual Boot με Windows στον ίδιο δίσκο

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#25]
Ελπίζω ότι μόλις ολοκληρωθεί η έκδοση v2.0 με την συνένωση του κώδικα, θα μπορούμε στην v3.0 με το εξωτερικό Conf να προσθέσουμε σενάρια για dualboot

**Comment by billniakas** [comment]
Έχω στο feature branch έναν advanced installer που δεν πειράζει τα υπάρχοντα partitions και δημιουργεί καινούρια. 

Το μόνο πράγμα που δεν ξέρω αν πρέπει κάνουμε, είναι αν πρέπει να δίνουμε δυνατότητα στο χρήστη να διαγράφει εξ ολοκλήρου το σκληρό και στη συνέχεια να προχωρά. 

Στην περίπτωση που δε θέλει να το κάνει κάνει νέα partitions αλλά το πρόβλημα μου είναι ο χώρος. Δηλαδή αν έχεις έναν SSD 250gb και έχεις στα windows 150 GB (από αυτά ελεύθερα τα 100), μπορείς να κάνεις ένα partition 150 GB;; Λογικά ναι, αλλά χρειάζεται επιπλέον testing.

**Comment by billniakas** [comment]
Στον ίδιο δίσκο το βασικό πρόβλημα που παρουσιάζεται είναι κατά το partitioning ώστε να μην πέσει επάνω στο partition των windows.

**Comment by billniakas** [comment]
Επιβεβαίωνω ότι dualboot γίνεται κανονικά σε 2 ξεχωριστούς δίσκους αλλά υπάρχει ένα μικρό bug που πρέπει να διορθωθεί. Σε δυο δίσκους /dev/sda(Windows) και /dev/sdb(Arch Linux) επειδή δεν είναι mount το partition των windows (/dev/sda1) κατά το install δεν το προσθέτει στον grub αλλά πρέπει να το κάνω εγώ χειροκίνητα. Δηλαδή μετά το πρώτο boot έκανα ``sudo mount /dev/sda1  /mnt`` και μετά ``sudo grub-mkconfig -o /boot/grub/grub.cfg`` για να μπει το entry.

Πρέπει να βρούμε έναν τρόπο κατά το lsblk να βλέπουμε πιο partition έχει windows ή αλλο λειτουργικό και να το κάνουμε mount για μη χρειάζεται να το κάνουμε χειροκίνητα.

**Comment by billniakas** [comment]
Ιδέα για dual boot
```
#!/bin/bash
lsblk | grep -oP sd\[a-z]\[1-9]+ | sed 's/^/\/dev\//' > disks.txt
while IFS='' read -r line || [[ -n "$line" ]]; do

  sudo mount $line /mnt | echo "Mounting...$line"
    
done < "disks.txt"
rm disks.txt
```
παίρνει όλους διαθέσιμους σκληρούς, και τους προσαρτά
φυσικά δεν μπορεί να προσαρτήσει το SWAP, αφού γίνει αυτό και λογικα θα προσαρτήσει και άλλες εγκαταστάσεις linux ή windows μόλις τρέξουμε  

``sudo grub-mkconfig -o /boot/grub/grub.cfg``

και φαντάζομαι οτι με reboot θα δουλέψει κανονικά

**Comment by cerebrux** [comment]
Προσωρινά ένα Workaround έχει προστεθεί στο develop https://github.com/CerebruxCode/Archon/commit/c73296c492db3546e087b6315d2e37fe97585755  το οποίο όμως είναι για **εγκατάσταση του Arch σε δεύτερο δίσκο**. Έτσι αναγνωρίζει την ύπαρξη άλλου λειτουργικού (windows, linux) στον πρώτο δίσκο επιλέγοντας στο Archon να **μπει ο grub στον πρώτο δίσκο**.

**Comment by cerebrux** [comment]
> Talk is cheap, show me the code
>                            _- Linus Torvalds_

Δεν φαίνεται κάποια δραστηριότητα στο Issue αυτό. Οπότε ήρθε το πλήρωμα του χρόνου να το κλείσει.

Σε περίπτωση που υπάρξει κάποιο ενδιαφέρον με Pull Request, θα ξανά ανοίξει
