### ISSUE TITLE
Αφαίρεση μηνυμάτων από την ping για τον έλεγχο σύνδεσης στο διαδίκτυο.

### ISSUE THREAD

**Issue by AntGeorge** [CerebruxCode/Archon#26]
Πιστεύω ότι θα ήταν πιο ωραίο να μην εμφάνιζε τα αποτελέσματα της εντολής ping και απλά να είχε το τελικό μήνυμα του ελέγχου.

Με ένα redirect του stdout και του stderr στην null:
<pre>ping -c 5 www.google.com <b>&></b> /dev/null</pre>

Δεν ξέρω αν πρέπει να ακολουθήσω την διαδικασία υποβολής για μια τόσο ασήμαντη και μικρή αλλαγή.

**Comment by cerebrux** [comment]
Νομίζω είναι καλή ιδέα αυτό που λες. Ας δούμε και τι θα πει ο @billniakas 

Υ.Γ.

> Δεν ξέρω αν πρέπει να ακολουθήσω την διαδικασία υποβολής για μια τόσο ασήμαντη και μικρή αλλαγή.

Δεν πειράζει αν είναι μικρή η και καθόλου. Για να υπάρχει ιστορικό αλλαγών, θα πρέπει ακόμα και για μια απλή ιδέα να υπάρχει αναφορά όπως το γράψαμε στο https://github.com/CerebruxCode/Archon/blob/master/CONTRIBUTING.md

Σκέψου κάτι να πάει στραβά στο μέλλον και να μην ξέρουμε απο που ξεκίνησε :)

**Comment by billniakas** [comment]
Συμφωνώ με την ιδέα του George.

**Comment by cerebrux** [comment]
Ευχαριστουμε για το patch ! :)
