### ISSUE TITLE
Περιγραφικά μηνύματα για την έκδοση v1.2

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#27]
Μια βελτίωση για Usability στα μηνύματα του Archon με προσθήκη Sleep εκεί που χρειάζεται κενά και λίγο πιο περιγραφικά μηνύματα (π.χ. βήμα 2/10).

**Comment by billniakas** [comment]
Διόρθωσα και μερικά ορθογραφικά/τυπογραφικά λάθη.
