### ISSUE TITLE
Η εγκατάσταση δεν ακυρώνεται όταν κάποια εντολή αποτύχει

### ISSUE THREAD

**Issue by AntGeorge** [CerebruxCode/Archon#29]
Προσπάθησα να κάνω εγκατάσταση σε δίσκο που είχε ήδη κάποιο partition με αποτέλεσμα οι εντολές **parted** και **mkfs** ναι με προειδοποιούν για αυτό και να μου δίνουν την επιλογή αν θέλω να συνεχίσω. Το πρόβλημα είναι ότι όπως φαίνεται και στην εικόνα αν επιλέξω "No" η εγκατάσταση συνεχίζει κανονικά χωρίς να διαμορφώσει σωστά τον δίσκο.

![screenshot from 2017-09-27 14-15-41](https://user-images.githubusercontent.com/12598031/30910936-5ccb04f8-a38f-11e7-8a9a-28188231ef52.png)

Νομίζω το πρόβλημα είναι ότι στις εντολές αυτές (**parted** και **mkfs**) δεν γίνεται κάποιος έλεγχος για το αν εκτελέστηκαν σωστά ή αν ο χρήστης τις ακύρωσε.

Μια λύση είναι στην αρχή του προγράμματος να βάλουμε **set -e** ούτως ώστε όταν κάποια εντολή αποτύχει το πρόγραμμα να κάνει exit. Αλλιώς μπορούμε ξεχωριστά για κάθε εντολή να ελέγχουμε αν εκτελέστηκε.

**Comment by billniakas** [comment]
Στην παρούσα φάση προτείνεται η εγκατάσταση μέσω του Archon να γίνεται σε σκληρό χωρίς κατατμήσεις. Αν δεις στο branch advancedinstaller προσπαθούμε να το κάνουμε πιο failproof για να μην υπάρξουν ακριβώς αυτές οι κακοτοπιές :)

Αν είδες μέσα στο script οι αριθμήσεις των σκληρών ξεκινούν από το 1 οπότε υπαινίσσεται ότι δεν υπάρχουν partitions. Βέβαια αυτό μπορεί να αλλάξει με ένα απλό editing στο script. Έτσι εγώ κατάφερα να κάνω dual boot με windows στον ίδιο σκληρό.

**Comment by cerebrux** [comment]
Αυτό εδώ 

> Μια λύση είναι στην αρχή του προγράμματος να βάλουμε **set -e** ούτως ώστε όταν κάποια εντολή αποτύχει το πρόγραμμα να κάνει exit.

μου άρεσε και θα το βάλω. Θα στείλω patch για να γίνει reference και οπότε θα το κλείσουμε το bug. 

Για τα υπόλοιπα, υπάρχει το Milstone 3.0 στο οποίο πλέον θα γίνεται έλεγχος σκληρού, dualboot και όλα τα μαγικά που ετοιμάζει ο @billniakas μόλις ενσωματώσουμε το develop:feature/advancedinstaller ( https://github.com/CerebruxCode/Archon/tree/feature/advancedinstaller ) στο master.
