### ISSUE TITLE
Εγκατάσταση σε Fast-mode

### ISSUE THREAD

**Issue by AntGeorge** [CerebruxCode/Archon#32]
Αν έχω καταλάβει σωστά την φιλοσοφία του project, θα ήταν ωραίο να βάλουμε μια παράμετρο (επιλογή) με την οποία το script θα εκτελείτε αποφεύγοντας τις εντολές sleep για να μην είναι τόσο χρονοβόρα η διαδικασία για αυτούς που θα το χρησιμοποιήσουν για πολλές εγκαταστάσεις.
Σε συνδυασμό με το εξωτερικό configuratio αρχείο θα ήταν μια καλή επιλογή.

**Comment by billniakas** [comment]
Καλή η ιδέα σου και για να την κάνω ακόμη πιο ελκυστική το Fast mode να έχει προεπιλεγμένο partitioning/χρήστη και ότι άλλο χρειάζεται ώστε να μην πατηθεί τίποτα μέχρι το reboot. Προς το παρόν εστιάζω στο branch που έχω τον advancedinstaller γιατί στους περισσότερους που πάνε να βάλουν Arch το κομμάτι που τους φοβίζει περισσότερο είναι το partitioning.

**Comment by AntGeorge** [comment]
Σωστά, το πιο σημαντικό κομμάτι είναι το dual boot. Απλά το έβαλα για μελλοντικό χαρακτηριστικό. Ας επανέλθουμε σε αυτό μετά την λειτουργιά για dual boot.

**Comment by cerebrux** [comment]
Έγινε μια μείωση του χρόνου που σπαταλάει το σύστημα για τo sleep
