### ISSUE TITLE
Διαγραφή και καθαρισμός στοιχείων που παραπέμπουν στο archon.2

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#33]

**Comment by billniakas** [comment]
Νομίζω ότι δε θέλει ενημέρωση το readme γιατί δεν έχει αλλάξει κάτι στον τρόπο που τρέχει το Archon.

**Comment by cerebrux** [comment]
Ναι, δεν αναφέρεται πουθενά. Θα το κρατήσω ανοιχτό, για να κάνουμε reference στα commit τον αριθμό 33 αν εμφανιστεί κάποιο bug και θα το κλείσουμε όταν είναι να βγει η v2.0
