### ISSUE TITLE
Εξωτερικό configuration

### ISSUE THREAD

**Issue by AntGeorge** [CerebruxCode/Archon#34]
Έχω ξεκινήσεις να το φτιάχνω, αυτήν την στιγμή είναι δυνατή η αυτοματοποίηση της εγκατάστασης του arch χωρίς επιλογές για dual boot. Θα περιμένω να τελειώσει το κομμάτι του dual boot για να προσθέσω τις αντίστοιχες επιλογές στο configuration.
Έχω φτιάξει ένα branch στο fork που έχω με όνομα external-conf οπότε μπορείτε να κάνετε και εσείς δοκιμές με αυτό.
Όλες οι επιλογές ρυθμίζονται από το αρχείο εκτός από τους κωδικούς χρήστη και root, τους οποίους πιστεύω για προφανείς λόγους θα ήταν καλύτερο να μην υπάρχουν στο αρχείο.

**Comment by billniakas** [comment]
Μια ιδέα για το εξωτερικό configuration. Να έχουμε το αρχείο ``archon.conf`` που θα λειτουργεί κάπως έτσι 
```
while IFS='' read -r line || [[ -n "$line" ]]; do
$line 
done < "archon.conf" 
```
όπου ``$line`` θα είναι η εντολή που θα έχουμε στο configuration. Το μόνο που με απασχολεί είναι το comment που θα βάζουμε γιατί θα αν διαβάζει γραμμή με comment θα πετάει λάθος.

**Comment by AntGeorge** [comment]
Έχω καιρό να ασχοληθώ με αυτό αλλά αν θυμάμαι καλά επειδή το *configuration* αρχείο στην ουσία δίνει μια προκαθορισμένη τιμή στις μεταβλητές που χρησιμοποιεί το *script* το μόνο που έκανα ήταν να εκτελέσω την εντολή *.* (ή *source* για bash) στο αρχείο.
Έχω κάτι έτοιμο για να κάνω PR αλλά το είχα αφήσει μέχρι να λειτουργήσει του dual boot mode.

**Comment by billniakas** [comment]
Ok @AntGeorge θα δω σύντομα το θέμα του dualboot  (να κάνω ένα VM με windows και να περάσω μετά Arch αν το παίρνει σωστά) και μετά αν είναι να το δούμε μαζί.

**Comment by cerebrux** [comment]
Δεν υλοποιήθηκε
