### ISSUE TITLE
ip address

### ISSUE THREAD

**Issue by amanouss** [CerebruxCode/Archon#39]
Εάν κάνεις εγκατάσταση και χρησιμοποιήσεις στατική ip, στο τέλος  στη ρύθμιση του δικτύου  το archon σε  γυρνάει dhcp, και έτσι στην επανεκκίνηση αναγκάζεσαι να κάνεις ρύθμιση δικτύου. Αυτό ίσως να μπορεί να διορθωθεί?

**Comment by AntGeorge** [comment]
Ναι σωστά, θα πρέπει να υπάρχει μια επιλογή για τον αν θέλει να έχει στατική ή δυναμική διεύθυνση και αν επιλέξει στατική να δώσει τις απαραίτητες πληροφορίες (ip, mask ...).

**Comment by cerebrux** [comment]
Κατά την εγκατάσταση με την χρήση του Archon σκοπός είναι να το βάλεις και να τελειώνεις. Όλες οι υπόλοιπες customιές που μπορούν να γίνουν έπειτα, είναι καλό να γίνουν μετά. 
Με λίγα λόγια, το Archon το χρησιμοποιείς επειδή θες να τελειώνεις με την εγκατάσταση σε 5-10 λεπτά για να ασχοληθείς έπειτα με το λειτουργικό όταν θα έχεις χρόνο και όρεξη.
