### ISSUE TITLE
Replace yaourt with aurman

### ISSUE THREAD

**Issue by giorgosioak** [CerebruxCode/Archon#40]
Yaourt is not safe for use according to arch wiki
https://wiki.archlinux.org/index.php/AUR_helpers#Discontinued_or_problematic

Its better to replace with aurman
https://aur.archlinux.org/packages/aurman/

**Comment by billniakas** [comment]
Είναι γνωστό το πρόβλημα με το yaourt, αλλά πρόβλημα είναι και ότι δεν μπορούμε σε root περιβάλλον να κάνουμε εγκατάσταση με το `makepgk`.

Όποιες προτάσεις ευπρόσδεκτες :)

**Comment by giorgosioak** [comment]
Ναι το παρατήρησα στην πορεία. ^_^

**Comment by cerebrux** [comment]
Fixed in 3fcad2cc838e43f3deaf5ba470f02fcd46a6767f
