### ISSUE TITLE
no module named reflector

### ISSUE THREAD

**Issue by DimitrisThanos** [CerebruxCode/Archon#41]
μολις δημιουργηθουν οι κατατμησεις  και ξεκινα την εγατασταση:
/usr/bin/python3 : no module named Reflector και σε πεταει εξω

**Comment by billniakas** [comment]
Δημήτρη έγινε comment το σχετικό κομμάτι μέχρι να δούμε τι θα κάνουμε. Η πορεία της εγκατάστασης ή η ταχύτητας δεν επηρεάζεται από αυτή τη μεταβολή.

**Comment by cerebrux** [comment]
Fixed in 2d86a9110cc3a39071e29eaaf196f9eb7e573bdb
