### ISSUE TITLE
Το yaourt δεν υποστηρίζεται πλέον

### ISSUE THREAD

**Issue by billniakas** [CerebruxCode/Archon#44]
Το yaourt δεν υποστηρίζεται από πλέον. Ή θα βάλουμε άλλον AUR helper ή θα το βγάλουμε εντελώς. Προτείνω να βάλουμε το ```aurman``` ή το ```yay```.

Το μόνο πρόβλημα μας είναι ότι το makepkg δεν υποστηρίζει root περιβάλλον. Άρα όταν μπαίνουμε στο εγκατεστημένο arch πρέπει με κάποιον τρόπο να βγαίνουμε από το root και να το εγκαθιστούμε

```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -r yay
```

**Comment by cerebrux** [comment]
Fixed 191e3ac058d14737479dcbac8578a04810b75796
