### ISSUE TITLE
Ερώτηση Feature Request

### ISSUE THREAD

**Issue by kwstas86** [CerebruxCode/Archon#45]
Γίνετε να κάνετε τον Archon έτσι ώστε να εμφανίζονται οι εντολές πριν από την εκτέλεση τους;

**Comment by AntGeorge** [comment]
Για αρχή νομίζω είναι καλό αυτό.
Αν και τις εντολές με pipeline τις εμφανίζει σαν 2 διαφορετικές.
Αν συμφωνείτε και εσείς @cerebrux @billniakas νομίζω ότι μπορεί να κλείσει το issue αλλιώς πείτε μου για οποιαδήποτε αλλαγή.

**Comment by billniakas** [comment]
Οι εντολές είναι αυτές που γράφονται και στο άρθρο για τη χειροκίνητη εγκατάσταση του Arch Linux. Δε θα δεις κάτι διαφορετικό.
