### ISSUE TITLE
Αδυναμία εύρεσης και τροποποίησης nvme δίσκων

### ISSUE THREAD

**Issue by JohnGavr** [CerebruxCode/Archon#48]
Στον κώδικα δεν συμπεριλαμβάνεται η ανάγνωση τον nvme δίσκων. Καθώς προχωράει η τεχνολογία όλο και περισσότεροι nvme δίσκοι θα εμφανίζονται και πρέπει να υπάρχει και αυτή η επιλογή για τους χρήστες.

**Comment by cerebrux** [comment]
Ωραία έγινε merge στο develop branch για να γίνει testing
