### ISSUE TITLE
Desktop Environment script

### ISSUE THREAD

**Issue by dimkatsi91** [CerebruxCode/Archon#52]
Init commit for Desktop Environment help script after base system installation ..

**Comment by cerebrux** [comment]
Ευχαριστούμε @dimkatsi91 Θα το τεστάρουμε !

**Comment by dimkatsi91** [comment]
Just test the last version, had forgotten a function call commented in main !

I also tested your script, installed successfully Arch in virtualbox VM, after that used my script and installed MATE DE in this VM.

Have a nice day,

Best Regards,
Dimosthenis Katsimardos

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cerebrux** [comment]
@dimkatsi91 Oh ! can you please verify that I merged the correct version on master and develop branches ? Did you pushed any pull requests ?

(P.S. Γιατί μιλάμε Αγγλικά ?? :P )

**Comment by dimkatsi91** [comment]
Hello,

Nai auto einai to sosto version opws vlepw.

H dunamh ths syni8eias I guess , haha !!

Best Regards,
Dimosthenis Katsimardos

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cerebrux** [comment]
Ωραία :) Όποτε κλείνουμε εδώ.
