### ISSUE TITLE
Εγκατάσταση σε VM με EFI (Επιλογή δίσκου)

### ISSUE THREAD

**Issue by teras** [CerebruxCode/Archon#58]
Προσπάθησα να εγκαταστήσω το archon σε VM από Parallels αλλά δυστυχώς το σύστημα παρουσιάζει πρόβλημα αμέσω μετά την εύρεση  ως εξής:

```
Χρησιμοποιείς PC με UEFI

Error: Could not stat a device a - No such file or directory.
Retry/Cancel?
```
και μένει εκεί για πάντα

Στέλνω και screenshot από τη διαδικάσία

<img width="525" alt="Screen Shot 2020-05-08 at 5 57 15 PM" src="https://user-images.githubusercontent.com/592568/81418612-9b2eba80-9155-11ea-9581-b8c2ad0a844b.png">

Καμμία ιδέα;

**Comment by billniakas** [comment]
Αντί για a πρέπει να δώσεις /dev/sda

**Comment by cerebrux** [comment]
@teras ευχαριστούμε για το report. Αν και δεν είναι bug αλλά λάθος  του χρήστη, παρόλα αυτά ανέδειξες ένα σημαντικό UX πρόβλημα που θα το διορθώσουμε στην επόμενη έκδοση για να είναι πιο επεξηγηματική η επιλογή δίσκου

**Comment by cerebrux** [comment]
@teras με την νέα έκδοση https://github.com/CerebruxCode/Archon/tree/v3.0.1 διορθώθηκε προσωρινά μέχρι να φτιάξουμε έναν καλύτερο τρόπο επιλογής δίσκων. 
Αν έχεις να προσθέσεις κάτι παραπάνω, μην διαστάσεις να σχολιάσεις το issue !
Εσύ απλώς κατεβάζεις, πάλι με την ίδια εντολή το archon όπως γράφουμε στο readme ή απλά αν το έχεις το παλιό γράφεις την πλήρη διαδρομή του δίσκου σου π.χ. /dev/sda

**Comment by cerebrux** [comment]
η νέα έκδοση #66 πλέον δεν απαιτεί να γράψεις διαδρομή αλλά να επιλέξεις αριθμό δίσκου
