### ISSUE TITLE
Post install - Εφαρμογές

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#60]
Εδώ μπορούμε να συζητήσουμε το post install script για εφαρμογές μετά την εγκατάσταση της βάσης του Arch

https://github.com/CerebruxCode/Archon/commits/develop/post_programs_installer.sh

**Comment by cerebrux** [comment]
@dimkatsi91 θυμήσου να βάζεις --no-confirm στις pacman εντολες. π.χ.

```
sudo pacman -S --noconfirm vlc
```
Με το σκεπτικό ότι εφόσον ο χρήστης επέλεξε να εγκαταστήσει το VLC από τις επιλογές που του δίνουμε, δεν χρειάζεται να τον ρωτάει ο Pacman δεύτερη φορά

**Comment by dimkatsi91** [comment]
Οκ, ναι πράγματι καλό είναι να μην ζητείται 2η φορά 'y', επίσης μπορεί να αφαιρεθεί και το print-out των commands μέσω '&>/dev/null' . Επίσης, το επόμενο που μπορεί να προστεθεί είναι η δυνατότητα εγκατάστασης ενός Document Reader (Libre/Open Office) ..

**Comment by cerebrux** [comment]
Το αποτέλεσμα των εντολών δεν πρέπει σε καμία περίπτωση να κρύβεται ! Είναι ενάντια του KISS. Μιλάμε με αλλά λόγια για Arch linux όπου πρέπει να βλέπεις ότι όλα πάνε καλά.

**Comment by dimkatsi91** [comment]
Πράγματι, καλό είναι να φαίνονται οι εκτελούμενες εντολές, οπότε και τις επανέφερα μαζί με μια βελτίωση στο post_programs_installer.sh ; οι αλλαγές βρσκονται στο forked repo.

**Comment by cerebrux** [comment]
@dimkatsi91 Είδα εκτενώς τον κώδικα. Κάνε μια προσπάθεια να τα περάσεις όλα σε case π.χ. όπως εδώ https://github.com/CerebruxCode/Archon/blame/432c613c2d24057334c659f280c624c17c09da58/archon.sh#L126
 
Για να είναι πιο εύκολη η ανάγνωσή του κώδικα και η συνεισφορά από άλλους. Με τα πολλά if - else καταλήγει σε spaghetti :P

**Comment by dimkatsi91** [comment]
@cerebrux μου αρέσουν και τα δύο για αυτό άλλωστε και έγραψα το ένα έτσι και άλλο σπαγγέτι όπως λες  .. :)
Και επίσης για αυτό τα έχω και στο δικό μου forked repo. Οποιεσδήποτε αλλαγές δεκτές ..

Επίσης τα αρχεία : 
https://github.com/CerebruxCode/Archon/blob/develop/postinstall/post_programs_installer.sh 
και 
https://github.com/dimkatsi91/Archon/blob/develop/post_programs_installer.sh
δεν είναι aligned.

**Comment by cerebrux** [comment]
> @cerebrux μου αρέσουν και τα δύο για αυτό άλλωστε και έγραψα το ένα έτσι και άλλο σπαγγέτι όπως λες .. :)

XAXAX γούστα είναι αυτά... απλά εμείς ακολουθούμε όσο μπορούμε το readability και να μπορεί πχ να βάζει εύκολα μια δυο γραμμές σε ένα case με το γραφικό περιβάλλον που θέλει και να πάιζει.

> Και επίσης για αυτό τα έχω και στο δικό μου forked repo. Οποιεσδήποτε αλλαγές δεκτές ..

Εννοείται ο καθένας ότι θέλει κάνει στο repo του :+1:  :P Γιαυτό και αλλάγες μπορώ να προτείνω μόνο σε ότι γίνεται pull request για merge
 
> Επίσης τα αρχεία :
> https://github.com/CerebruxCode/Archon/blob/develop/postinstall/post_programs_installer.sh
> και
> https://github.com/dimkatsi91/Archon/blob/develop/post_programs_installer.sh
> δεν είναι aligned.

Λες να μου ξέφυγε κανένα pull request για merge ή να χάθηκαν οι αλλαγές στα merge ?
Καλό είναι κάθε φορά πριν ξεκινήσει αλλαγές στον κώδικα να κάνεις pull απο το develop branch για να πατάς πάνω τους και να μην πέφτουμε σε merge conflict.
Επομένως αν πιστεύεις ότι το αρχείο πρέπει να αλλαχτεί στείλε pull. 
Y.Γ.  φάκελος post install θα περιλαμβάνει αρχεία και scripts για "post install", που δεν χρειάζεται να είναι στο main

**Comment by ditikos** [comment]
Πολυ καλος installer -- οι προτασεις μου για post installer:

- Defaulting editor: vim / nano / emacs
- Εγκατασταση yay η άλλου προγραμματος για το AUR

**Comment by cerebrux** [comment]
Έχει σταματήσει να γίνεται maintained οπότε ειναι obsolete.
