### ISSUE TITLE
(Πολυγλωσσικό) Δυνατότητα επιλογής γλώσσας μηνυμάτων

### ISSUE THREAD

**Issue by astrolavos1998** [CerebruxCode/Archon#68]
Θα μπορούσαμε στην αρχή της εκτέλεσης του Archon script να ζητάμε από τον χρήστη να επιλέγη γλώσσα εγκατάστασης του Archon.
Η ιδέα είναι να έχουμε ανάλογο αριθμό arrays με τις γλώσσες. Όπου υπάρχει μήνυμα μέσα στον κώδικα του script θα αντικατασταθεί από μια μεταβλητή τύπου array που θα έχει πάρει τιμές από το αντίστοιχο array της επιλεγμένης γλώσσας.
str_gr --> περιέχει τα μηνύματα όλα στα ελληνικά.
str_en --> περιέχει τα μηνύματα όλα στα αγγλικά.
Επιλογή    [  1. Ελληνικά Gr  ]  -  [  2. English En  ]
Αν είναι το 1 τότε το str_lang θα παίρνει όλες τις τιμές του str_gr
Αν είναι το 2 τότε το str_lang θα παίρνει όλες τις τιμές του str_en
Εδώ θα ξεκινάει ο ήδη υπάρχων κώδικας του Archon script και όπου υπάρχει μήνυμα θα έχει αντικατασταθή από το ανάλογο στοιχείο του πίνακα str_lang.
Έτσι θα έχουμε πολυγλωσσικότητα με έναν κώδικα και όταν θα θέλουμε να προσθέσουμε μια νέα γλώσσα απλά θα προσθέτουμε ένα πίνακα με την μετάφραση της επιθυμητής γλώσσας.
Παραθέτω και ένα αρχικό δείγμα του κώδικα χωρίς προστασία από λάθος επιλογή από τον χρήστη κτλ, ώστε έτσι να μπούμε όλοι στο πνεύμα.

ΥΓ: η μετάφραση μπορεί να γίνει ακόμη και με google translate αφού τα μηνύματα ήδη είναι πολύ απλά και μπορούν να γίνουν ακόμη πιο απλά, έτσι ώστε να είναι πιο εύκολη και αξιόπιστη η google μεταφρασή τους. ;-)
[test.txt](https://github.com/CerebruxCode/Archon/files/4672649/test.txt)

**Comment by astrolavos1998** [comment]
Τρέχω στο τέρμιναλ γραμμή γραμμή τον κώδικα και όλα μια χαρά. Όταν τον ίδιο ακριβώς κώδικα τον τρέχω σαν αρχείο .sh τότε βγάζει το λάθος Syntax error: "(" unexpected
```
$ a=("foo 1" "bar two")
$ b=("${a[@]}")
$ echo "${b[1]}"
bar two
$ echo "${b[@]}"
foo 1 bar two
$
```

**Comment by cerebrux** [comment]
@billniakas θυμάσαι που το συζητούσαμε ! Να λοιπόν όταν υπάρχει ενδιαφέρον ποσό ωραίες ιδέες πέφτουν στο τραπέζι !!! Μπράβο @astrolavos1998

**Comment by astrolavos1998** [comment]
Τελικό δείγμα του κώδικα με τα χρώματα του Arch Linux τόσο στα μηνύματα όσο και στο Archon λογότυπο, για ευνόητους λόγους.
[Δείγμα του κώδικα επιλογής γλώσσας](https://github.com/CerebruxCode/Archon/files/4676457/test.txt)

**Comment by billniakas** [comment]
Προφανώς το λογότυπο του Archon δεν αλλάζει, αλλά τα υπόλοιπα δείγματα κώδικα φαίνονται καλα.

**Comment by astrolavos1998** [comment]
> Προφανώς το λογότυπο του Archon δεν αλλάζει, αλλά τα υπόλοιπα δείγματα κώδικα φαίνονται καλα.

Άρα προχωρώ και κάνω τις αλλαγές στον κώδικα του Archon 4.0 χωρίς να πειράξω το λογότυπο και ανεβάζω το αρχείο εδώ; Πως γίνετε φιλαράκι μου η διαδικασία;

**Comment by cerebrux** [comment]
> Πως γίνετε φιλαράκι μου η διαδικασία;

check https://github.com/CerebruxCode/Archon/blob/master/CONTRIBUTING.md

**Comment by astrolavos1998** [comment]
Μετά από πολλές προσπάθειες, ο κώδικας για την πολυγλωσσικότητα του Archon 4.0 έγινε ΑΛΛΑ αντιμετωπίζω ένα πρόβλημα που δεν μπορώ μετά από 1 εβδομάδα προσπαθειών να επιλύσω.
Ενώ ξεκινάει η εκτέλεση του script κανονικά ,όταν φτάνει στην εκτέλεση του function chroot_stage τότε ΔΕΝ εμφανίζει τα echo με τις μεταβλητές από τον πίνακα της επιλεγμένης γλώσσας str_lang[i] (όπου i είναι η αντίστοιχη γραμμή από το αρχείο κειμένου της επιλεγμένης γλώσσας, κατά μείον ένα).
Έκανα πολλές αλλαγές, δοκιμές και προσπάθειες αλλά δεν μπορώ να λύσω το πρόβλημα.
Πιστεύω πως πρέπει να δομηθεί καλύτερα ο κώδικας του script ώστε να αποκτήσουμε καλύτερη εικόνα και έλεγχο της ροής.
[archon.lang.txt](https://github.com/CerebruxCode/Archon/files/4716049/archon.lang.txt)


![problem-language-1](https://user-images.githubusercontent.com/25374331/83501856-6bab6d80-a4c9-11ea-9464-4834101dfc0b.jpg)

**Comment by billniakas** [comment]
Πρέπει να κάνεις export τη συνάρτηση που διαχειρίζεται τις μεταβλητές αλλαγής γλώσσας.
Επιπλέον δεν είναι σωστή πρακτική να ποστάρεις ένα txt με τον κώδικα. 

Προσωπικά δεν έχω καταλάβει πως λειτουργεί ο κώδικας σου, βάλε τον απαραίτητο σχολιασμό.

Κάνε τις αλλαγές στο forked αποθετήριο σου, κάνε τις δοκιμές σου και μετά ζήτα pull request

**Comment by cerebrux** [comment]
Δεν έχει γίνει maintained
