### ISSUE TITLE
Αδυναμία αναγνώρισης δίσκων

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#69]
Αυτή την στιγμή φαίνεται υπάρχει πρόβλημα αναγνώρισης δίσκων Nvme σε UEFI.

Απο το ιστορικό φαίνεται οτι προκλήθηκαν από τo παρακάτω merge:

https://github.com/CerebruxCode/Archon/commit/e83db574718bfad3664a00d49cc18216b82266a8?diff=split#diff-3496f46409c23dd2361aae2c7d54e00aR661

**Comment by cerebrux** [comment]
Διορθώσεις μέχρι τώρα : 

- https://github.com/CerebruxCode/Archon/commit/0c6ebb03b207d3acedc27f9e010e6cbfdb61fbf7
- https://github.com/CerebruxCode/Archon/commit/e3759ef859beca0230e42121404e459681a01f07
- https://github.com/CerebruxCode/Archon/commit/825ac5241e8d2039e7eaf2a844542f7a3214b42f

**Comment by cerebrux** [comment]
@billniakas check this 3.0.1 release before the bug https://github.com/CerebruxCode/Archon/blob/7f7dd3693a311a1145e49dbcc66dad042079f5df/archon.sh#L402

**Comment by cerebrux** [comment]
@dimkatsi91 Έχει μπει η απαραίτητη διόρθωση #71 στο κομμάτι της αναγνώρισης δίσκων NVME. Σου είναι εύκολο να το τεστάρεις μια τελευταία φορά και εσύ να δούμε αν εμφανίζει κάποιο πρόβλημα σε εσένα μιας και το πρόβλημα φαίνεται να προέκυψε με το refactoring που έκανες από την γραμμή 628 (BIOS / UEFI checking)

**Comment by dimkatsi91** [comment]
@cerebrux να το τεστάρω οκ, απλά δώσε λίγες παραπάνω πληροφορίες σχετικά με τις προδιαγραφές του συγκεκριμένου τεστ, διότι όλες οι δοκιμές που έχω κάνει με τα σκριπτάκια είναι σε VMs και όχι σε πραγματικό HW.

**Comment by cerebrux** [comment]
> προδιαγραφές σε VMs

Οι συνδυασμοί που δοκιμάζουμε είναι:

- BIOS GPT
- BIOS MBR
- Uefi με nvme disk
- Uefi με ssd disk

...κλπ Μας νοιάζει να βλέπουμε ότι ξεπερνάει τι στάδιο που εξετάζουνε χωρίς κάποιο πρόβλημα (πχ εδώ εξετάζουμε το στάδιο που εμφανίστηκε το bug) Από εκεί και πέρα στην παρούσα φάση του τεστ δεν μας ενδιαφέρει κάποιο άλλο χαρακτηριστικό του VM :)

**Comment by dimkatsi91** [comment]
Σε VirtualBox από Linux Host έχουν δοκιμαστεί επιτυχώς τα παρακάτω σενάρια κάνοντας χρήση του τελευταίου κώδικα από το branch 'develop':

- BIOS GPT

- BIOS MBR

- Uefi με nvme disk

- Uefi με ssd disk

Το script προχώρησε κανονικά στο σημείο όπου ξεκινάει η εγκατάσταση του arch και προτρέπει για καφεδάκι :)

**Comment by cerebrux** [comment]
Τέλεια ! Όποτε ήρθε η ώρα για να το κάνω merge στο Master και να βγει η v4.0.1 !

Μπράβο σε όλους σας !

**Comment by dimkatsi91** [comment]
Έχω κάνει εγκατάσταση σεπραγματικό HW κάνοντας χρήση του σκριπτ από το branch develop και απέτυχε να σετάρει την ασύρματη κάρτα δικτύου, επίσης έβγαλε μνμ πως πέτυχε, αλλά φάνηκε από του printout των commands πως απέτυχε.

Update 30/05/2020: Επανεκκίνηση του συγκεκριμένου λαπτοπ, στο οποίο είχε πραγματοποιηθεί εγκατάσταση στην οποία είχε αποτύχει το σετάρισμα της ασύρματης κάρτας δικτύου, απέτυχε και πλέον δε μπουτάρει καν.
