### ISSUE TITLE
Κατάργηση του systemd-swap

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/Archon#94]
Ανάλογα με το σύστημα αρχείων που θα επιλέξει ο χρήστης διαφέρει και ο τρόπος που πρέπει να ενεργοποιείται το systemd swap. Επίσης ο σύγχρονος πλέον τρόπος είναι η δημιουργία ενός swap file αντί για partition

Για παράδειγμα η ενεργοποίηση του swapfc που γίνεται από το archon δεν είναι συμβατό με το BTRFS.

Προτείνω το εξής :

- Ρωτάει τον χρήστη αν θέλει swap
- Περιμένει έναν αριθμό **σε MB**
- Αν δώσει 0 (μηδέν) σημαίνει δεν θέλει και άρα δεν δημιουργείται swap file
- Αν δώσει έναν αριθμό, δημιουργείται ένα αντίστοιχο swapfile και γίνεται η προσθήκη του  στο /etc/fstab

Πρέπει όμως να διερευνηθεί αν το swap file δημιουργείται με διαφορετικό τρόπο ανάλογα με το σύστημα αρχείων που έχει επιλεχτεί.

Έστω ότι η απάντηση που δίνει ο χρήστης αποθηκεύεται στην **$swap_size**

NOTE: _You shouldn’t use the fallocate command to create your swapfile on XFS and F2FS._

1. Για ext4, xfs, f2fs
```
dd if=/dev/zero of=/swapfile bs=1M count=$swap_size status=progress
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile # ίσως δεν έχει νόημα να είναι ενεργό κατά την εγκατάσταση
echo '/swapfile none swap defaults 0 0' >> /etc/fstab
```
2. Για btrfs
Note: The swap file cannot be on a snapshotted subvolume. The proper procedure is to create a new subvolume to place the swap file in.
```
truncate -s 0 /swapfile
chattr +C /swapfile
btrfs property set /swapfile compression none
dd if=/dev/zero of=/swapfile bs=1M count=$swap_size status=progress
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile # ίσως δεν έχει νόημα να είναι ενεργό κατά την εγκατάσταση
echo '/swapfile none swap defaults 0 0' >> /etc/fstab
```
Info : https://wiki.archlinux.org/index.php/Swap#Swap_file

**Comment by cerebrux** [comment]
@billniakas @JohnGavr ενημέρωσα το σχόλιο με οδηγίες

**Comment by JohnGavr** [comment]
Στην περίπτωση του btrfs πάλι με dd θα προσδιορίζουμε το μέγεθος;
`dd if=/dev/zero of=/swapfile bs=1M count=$swap_size status=progress`
